from distutils.core import setup
setup(
  name = 'Yowsup',
  packages = [
    'Yowsup',
    'Yowsup.Auth',
    'Yowsup.Auth.mechanisms',
    'Yowsup.Common',
    'Yowsup.Common.Http',
    'Yowsup.ConnectionIO',
    'Yowsup.Contacts',
    'Yowsup.Interfaces',
    'Yowsup.Interfaces.Dbus',
    'Yowsup.Interfaces.Lib',
    'Yowsup.Media',
    'Yowsup.Registration',
    'Yowsup.Registration.v1',
    'Yowsup.Registration.v2',
  ],
  version = '0.2',
  maintainer = 'Julian Perelli',
  maintainer_email = 'jperelli@gmail.com',
  description = 'A library to use whatsapp from python',
  url = 'https://github.com/jperelli/yowsup',
  download_url = 'https://github.com/jperelli/yowsup/tarball/0.1',
  keywords = ['whatsapp', 'API', 'wrapper'],
  classifiers = [],
)
